appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NAb4BaY3ypPmp4Y0ejTTNJ7p0X4vi/cSYeMVHbd5i36eOfRA2ZP+P90pXPGm0srCLhIDwZ90BxCeYH0hLAzvWPM48u0hj4qhgShCO0AiUGvHSPqi5Gn0GA127lHm5W9iuUW2I1OHyRnrOgEJqsWyvl1Uy8aeALWzQASKmt7oTbePPkG0nZFQoxf5Md9tMdzH28BxkmD5oB/WD7zVWTQKOoTQ4zCohpdHbZYwkzenGVkSglpg+6pP+4mrmI0snnV60qfPSEC/wByatdyMWIlISCLHOrlIbR1j2EQjnppCR4p2UMqMUYjHbeghcEWgcxXoAXlGsu57AjJEU2ukqjFCe/rwIAd7QFUXWNWmOfvSvTDl/HFDAte+j5wo/DAg0t4nv5UJZcTFVNxD4XgaMZQxTnjJX6v6e+mGpEKwd/k8wEar85rELxuxbM9BGaPhVffsp3VB69ZGiq+6X/2IvVBHpGx8I3nowYJfHIZbnyVb90a9GFM0BZoRazoDNYPxIAOp6k+0l5QoU+Lc/8pEh1b1x7EGdXFjzWyVchbvvbyBINkwAyicevawAPAqTyogMKGY3BpKfvtLxtunlQrhynD6s1WtzenO5zoTWOQKlSDoHGVmgpqHSm0nFiH1CzLaycEweaLs9MY63gadUvtDRDRllH7i1+a9IeKcaLjJAFeP6Eg=}
