travis:
  secure:
    BINSTAR_TOKEN: hu1RHRpo7CXzccE5R8+LQBhTk+Nxn7RyNDvlA2GCF/QQChkzeAXC9koXeEyeiXEvWn50t8JxuNbW5wgi5IIpiJrppjGGpXUyQ/DRS8/3tNQV1E+/4rtYfFJqVt1uAl0gcP1/TCaodxvhdAj7YzlFtOXKt3zyEb98CA7lvuKic8r/ncjyTZQLI6xsbSYrkDGM/rPEFlE0X2lakaCPwGEd3VdXyXniwNUCIW9pifPHkDkMFrBuWaqgFIx41GkmcW8FUZnIUkG9/zjZFz3v5BaUcguZDC3BnhcCeFvKvOpECh8+coKJNUOj2f6uJUPhFdl0WADFMOnhJHWZUjkbjKBr5B2F7qnxmj83obJDUIEjkmASj5/W4OqOmVZTTD4zChSySTnttV/kvdcKlwyLLUgROGvxKrSaFDuOMgP+KGTO2uK+uHduYnGIY7x1aTZIST8lwtUtVlicBF7r0zliN4Zz9m6sQO9RY438u8vwuBhUfKzLUsilUG67+YDiwo5hEZIaAV8HEPK08T+Y90QwQnxJgHHn61hWORY0FavN0Jjey/l1ligzosbIv0DqQGZGnKVT4xFm4a3ozuHEklNSGkt0w9fhWt+NUhlnKUO18V9C+p6DRH5cPRGgZ1fZFeE+PzHPit894lPLIl2vZ+5JRhCOO4REwVSeP1/p191JTWFpzDw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
